[Export]
baked_state = false
offer_binder = true
binder_url = "https://mybinder.org/build/gh/fonsp/pluto-on-binder/8345c9238da98fe56f3d0ee20200314769a7d893/"
slider_server_url = "https://plutocon2021-demos-sliderserver.plutojl.org/"
ignore_cache = [
    "index.jl",
]

[SliderServer]
exclude=[
    "index.jl",
    "Benjamin_Lungwitz_MarketRisk_time_series.jl",
]
